version: '3.8'

services:
  id:
    build: ./pursuit/id.pursuit/
    container_name: id.pursuit.local
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://*:5000
    networks:
      - modern_auth

  #APIS
  accounts.api:
    build: ./pursuit/accounts.api.pursuit/
    container_name: accounts.api.pursuit.local
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_URLS=http://*:5001
    networks:
      - modern_auth
  mortgage.api:
    build: ./pursuit/mortgage.api.pursuit/
    container_name: mortgage.api.pursuit.local
    ports:
      - 5002:5002
    networks:
      - modern_auth

  #Apps
  accounts.app:
    build: ./pursuit/accounts.app.pursuit/
    container_name: accounts.app.pursuit.local
    ports:
      - 5003:5003
    networks:
      - modern_auth

  coin.app:
    build: ./coin/app.coin/
    container_name: app.coin.local
    ports:
      - 5004:5004
    environment:
      - ASPNETCORE_URLS=http://*:5004
    networks:
      - modern_auth

  mortgage.app:
    build: ./pursuit/mortgage.app.pursuit/
    container_name: mortgage.app.pursuit.local
    ports:
      - 5005:5005
    environment:
      - ASPNETCORE_URLS=http://*:5005
    networks:
      - modern_auth

networks:
  modern_auth:
